version: "3"
services:
  my_postgres:
    image: postgres:14
    container_name: my_postgres
    env_file:
      - .env
    ports:
      - 5433:5432
  etl:
    image: flight_etl:1.0
    depends_on:
      - my_postgres
    env_file:
      - .env
